# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#     name: ${P_K8S_NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: ${P_K8S_NAMESPACE}
  labels:
    tier: app
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: php
    tier: app
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ${P_K8S_NAMESPACE}
  labels:
    tier: web
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: nginx
    tier: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: ${P_K8S_NAMESPACE}
  labels:
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
      tier: app
  template:
    metadata:
      labels:
        app: php
        tier: app
    spec:
      containers:
      - name: php
        image: ${P_OCIR_REGION_KEY}.ocir.io/${P_TENANCY_NAMESPACE}/${P_OCIR_REPO_NAME_PHP_ADB}:${BUILDRUN_HASH}
        env:
        - name: ADB_TNSNAME
          valueFrom:
            secretKeyRef:
              name: adb-secret
              key: ADB_TNSNAME
        - name: ADB_USER
          valueFrom:
            secretKeyRef:
              name: adb-secret
              key: ADB_USER
        - name: ADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adb-secret
              key: ADB_PASSWORD
        - name: TNS_ADMIN
          valueFrom:
            secretKeyRef:
              name: adb-secret
              key: TNS_ADMIN
        ports:
        - containerPort: 9000
      imagePullSecrets:
      - name: ${P_IMAGE_PULL_SECRET}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ${P_K8S_NAMESPACE}
  labels:
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
  template:
    metadata:
      labels:
        app: nginx
        tier: web
    spec:
      containers:
      - name: nginx
        image: ${P_OCIR_REGION_KEY}.ocir.io/${P_TENANCY_NAMESPACE}/${P_OCIR_REPO_NAME_NGINX}:${BUILDRUN_HASH}
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ${P_IMAGE_PULL_SECRET}
---